---
# Check remote environment
# @todo move config paths to config role
# @todo move files paths to files role

- name: "Check remote environment shared paths"
  stat:
    path="{{ path_root['remote'] }}/{{ env }}/shared/{{ item | dirname }}"
  register: shared_path
  failed_when: "shared_path.stat.exists == false"
  with_items: path_shared_paths
  when: "path_shared_paths is defined"

- name: "Check remote environment config files."
  stat:
    path="{{ path_root['remote'] }}/{{ env }}/shared/{{ item.value['dest'] | dirname }}"
  register: config_file
  failed_when: "config_file.stat.exists == false"
  with_dict: config | default({})
  when: "config is defined"

- name: "Check remote environment files paths."
  stat:
    path="{{ path_root['remote'] }}/{{ env }}/shared/{{ item.value }}"
  register: files_path
  failed_when: "files_path.stat.exists == false"
  with_dict: files | default({})
  when: "files is defined"