---
# Deploy files to environment

- name: Deploy files between environments.
  hosts: webserver
  any_errors_fatal: true

  vars_files:
    - vars/path.yml
    - vars/environments.yml
    - vars/config.yml
    - vars/files.yml
    - vars/database.yml

  vars_prompt:
    - name: "env_src"
      prompt: "Environment source"
      private: no
    - name: "env_dest"
      prompt: "Environment destination"
      private: no
    - name: "site"
      prompt: "Environment site"
      default: "default"
      private: no


  roles:
    - { role: env_requirements, env: "{{ env_src }}" }
    - { role: files_requirements, env: "{{ env_src }}" }
    - { role: env_requirements, env: "{{ env_dest }}" }
    - { role: files_requirements, env: "{{ env_dest }}" }
    - { role: files_deploy, env_src: "{{ env_src }}", env_dest: "{{ env_dest }}" }