---
# Remove old releases.

- name: Clean up releases
  shell: ls -1dt {{ deploy_releases_path.stdout }}/* | tail -n +{{ deploy_keep_releases | int + 1 }} | xargs -I % sh -c 'chmod -R 755 %; rm -rf %;'
  when: deploy_keep_releases > 0