---
# Deploy remote code to environment

- name: Rsync application files from remote to remote shared copy
  synchronize:
    src="{{ path_root['remote'] }}/{{ env_src }}/{{ path_public }}/"
    dest="{{ deploy_shared_copy_path.stdout }}"
    set_remote_user="{{ deploy_rsync_set_remote_user }}"
    recursive=yes
    delete=yes
    archive=yes
    compress=yes
  delegate_to: "{{ inventory_hostname }}"