---
# Config variables.

# config:
#   default:
#     src: "default/settings.env.php.j2" # Project settings path template relative from templates.
#     dest: "sites/default/settings.env.php" # Project settings paths relative from path.local.public.