---
# Environment checks

- name: Check config is defined.
  fail: msg="Config {{ env }} {{ item.key }} is not defined"
  when: item.key not in config
  with_dict: config | default({})

- name: Check for local config template
  local_action: stat
    path="{{ playbook_dir }}/templates/{{ item.value['src'] }}"
  register: config_template_path
  failed_when: config_template_path.stat.exists == False
  with_dict: config | default({})