---
# Create on environment

- name: Create config directory
  file:
    path="{{ path_root['remote'] }}/{{ env }}/shared/{{ item.value['dest'] | dirname }}"
    state=directory
  with_dict: config | default({})

- name: Create config file
  template:
    src="{{ playbook_dir }}/templates/{{ item.value['src'] }}"
    dest="{{ path_root['remote'] }}/{{ env }}/shared/{{ item.value['dest'] }}"
  with_dict: config | default({})