---
# Environment controller

- debug: var=env_src
- debug: var=env_dest

- include: local.yml
  when: env_src == 'local' and env_dest in environments

- include: remote.yml
  when: env_src in environments and env_dest in environments